### ISSUE TITLE
[Todo]: things to implement

### ISSUE THREAD

**Issue by sammaji** [ExhibitHQ/ExhibitHQ-old#27]
- [ ] Banner
- [ ] Profile Pic
- [ ] Video Introduction
- [ ] User ID
- [ ] Name + About Section 
- [ ] Slugs
- [ ] Tech Stack
- [ ] Blogs (hashnode / devto)
- [ ] Email Verification (Blue Tick)
- [ ] Github Repo (Projects)
- [ ] Certification
- [ ] Achievements
- [ ] Testimonial Section
- [ ] Table of Contents (Sidenav)
- [ ] Collaborator
- [ ] Location
